package com.app_template.App_Template.enums;

public enum ActionType {
    LOGIN,
    LOGOUT,
    REGISTER,
    UPDATE_PROFILE,
    CHANGE_PASSWORD,
    ADD_TO_CART,
    REMOVE_FROM_CART,
    UPDATE_CART_QUANTITY,
    ADD_TO_WISHLIST,
    REMOVE_FROM_WISHLIST,
    VIEW_PRODUCT,
    CREATE_ORDER,
    CANCEL_ORDER,
    VIEW_ORDER,
    CHANGE_THEME,
    CHANGE_LANGUAGE,
    DELETE_ACCOUNT,
    SEARCH_PRODUCTS,
    VIEW_CART,
    VIEW_WISHLIST,
    CHECKOUT_STARTED,
    CHECKOUT_COMPLETED
}

